import * as Localization from "expo-localization";
import i18n from "i18n-js";
import { AsyncStorage } from "react-native";

const en = {
  username: "Username",
  phone: "Phone",
  gold: "Gold",
  Ingots: "Alloys",
  no_cat: "No Categories",
  no_image: "No Image",
  search: "Search the map",
  order: "Orders",
  new: "New",
  approved: "Approved",
  disapproved: "Rejected",
  check_field: "Please ensure all fields are entered",
  login: "Login",
  fail_login: "login failed",
  go_to_home: "You will be directed to the main page",
  error_login: "Wrong email or password",
  email: "Email",
  password: "Password",
  forget_password: "Forget Password ?",
  no_account: "Dont have an account?",
  create_account: "Create an account now",
  forget_password_title: "Forget Password",
  forget_password_des: "You will receive an email on the email you entered",
  send: "Send",
  resend: "Resend",
  signUp: "Create a new account",
  signUp_des: "Enter your information",
  agree: "I agree",
  Privacypolicy: "Privacy policy",
  signAlreadyAccount: "Do you have an account ?",
  signAlreadyAccountNo: "Dont have an account?",
  signlogin: "Enter your phone number to log in",
  sign_done_des:
    "By pressing the follow button you will receive a message to verify the phone",
  sign_done: "the registration is done",
  check_username: "Please check the username field",
  check_phone: "Please check the phone field",
  check_email: "Please check the email field ",
  check_password: "Password must contain at least 7 digits",
  user_policy_check:
    "Registration is only possible by agreeing to the terms of use of the application",
  no_order: "No Items",
  number_order: "Order number",
  date_order: "Order Date",
  name_order: "Order Name",
  total: "Total",
  no_item: "No Item",
  show_item: "Browse Products ",
  cart: "Cart",
  confirm: "Confirmed",
  reject: "rejected",
  reject_des:
    "You have a previous order that has not been confirmed, please wait for it to be confirmed",
  confirm_des:
    "Your order has been sent to the administration, it will be reviewed and answered",
  product: "Product",
  all_product: "All Product",
  stores: "Stores",
  cat_stores: "Store Categories",
  all_cat_stores: "All Categories",
  alloy_product: "Alloy products",
  gold_product: "Gold products",
  other_product: "Other products",
  add_to_cart: "Add to cart",
  product_same: "Similar products",
  alloy: "Alloys",
  add_done: "Added successfully",
  add_done_des:
    "The product has been added to the cart, you can see all the products in the basket",
  profile: "Profile",
  favorite: "Favorite",
  gold_price: "Price Gold",
  offers: "Offers",
  logout: "Logout",
  suggision: "Complaint or Suggestion",
  help: "Help",
  contact: "Contact Us",
  About_Us: "About Us",
  share: "Share",
  language: "Language",
  advertisment: "Advertisment",
  orders: "My orders",
  special_request: "Add a special request",
  send_done: "Sent succesfully",
  send_done_des: "The data has been successfully sent to the administration",
  address: "Address",
  description: "Description",
  title: "Title",
  title_pro: "Title Suggestion",
  title_com: "Title complaint",
  des_pro: "Description Suggestion",
  des_com: "Description complaint",
  Complaint: "Complaint",
  Suggestion: "Suggestion",
  Skip: "Skip",
  edit_profile: "Edit Profile",
  last_updated: "Last updated",
  caliber: "Caliber",
  price: "Price",
  sum: "Sum",
  confirmCart: "Confirm",
  login_order: "Login to view your Orders",
  notification: "Notification",
  SettingApp: "Please wait , the application is being prepared",
  change_photo: "Change photo",
  save: "Save",
  save_done: "saved",
  save_done_des: "The data was saved successfully",
  no_id_save_cart: "You cannot add to cart, log in first",
  gold_text:
    "Browse all gold rankings and products number in addition to the cart Submit a purchase order for the product  ",
  Categories: "Categories",
  alloy_text:
    "Browse all categories of bullion and alloy products of all kinds, add products to the basket and place an order",
  zinah: "Zinah jewelry store",
  submit_follow_up_request: "Submit a sale order",
  quantity: "Quantity",
  Tons: "Tons",
  your_map: "Your site",
  payment_type: "The way you prefer to receive the payment",
  cash: "Cash",
  change: "Change",
  contact_customer_service: "Contact customer service",
  send_email: "Send email",
  hide: "Hide",
  select_payment_method: "Select a payment method",
  cash_method: "Payment upon delivery",
  add_bank: "Add a bank account",
  add_bank_new: "Add a new bank account",
  done: "Done",
  edit: "Edit",
  delete: "Delete",
  Account_management: "Account management",
  account_owner: "Account owner name",
  number_account: "Account number",
  bank_name: "Bank Name",
  add_done: "Added",
  add_done_des: "Added successfully !",
  history: "History",
  receive_offers: "The stage of receiving offers",
  on_way: "on way",
  on_site: "on site",
  ladder: "delivred",
  canceled: "canceled",
  rejected_user: "Rejected",
  deliverd_on: "Was delivered in",
  order_id: "Order number",
  price_order: "Transaction price",
  details_order: "View order details",
  order_status: "Orde status",
  order_date: "Order date",
  date_deliverid: "Receiving date",
  location_in_map: "Location on the map",
  order_details: "Order Details",
  follow_order: "Follow your order",
  no_price: "",
  purchase_offer: "Purchase offer",
  Cancelling_order: "Cancelling order",
  show: "Show",
  approv: "Acceptance",
  rejec: "Refusal",
  Communication_service: "Communication with customer service",
  done_order: "Your request has been sent successfully",
  done_order_des:
    "It may take 1 - 24 business hours for you to get the bid. For inquiries you can contact with",
  customers_service: "customers service",
  name: "Name",
  address: "Your address in detail",
  my_address: "My Address",
  select_map: "Determine your location",
  select_map_done: "Selection successful",
  hello_coi: "you welcome in COI",
  sign: "new account",
  check: "Check",
  check_phone: "Verify the phone number",
  check_phone_des: "Enter the verification number sent to your phone",
  add_code: "Enter the code",
  add_code_des: "Enter the code to be able to change your number",
  success: "Success",
  success_des: "Success !",
  errorr: "Error",
  errorr_des: "The code you entered is wrong!",
  rating_success: "Congratulations",
  rating_success_des: "The deal was successfully completed",
  your_opinion: "your opinion matters",
  rating_text_success: "Rated",
  rating_text_success_des:
    "Your evaluation of the order has been added successfully !",
  Home: "Home",
  ChangeNumber: "Change Number",
  AddBank: "Payment methods",
  ChangeLanguage: "Change Language",
  UserPolicy: "Privacy policy and terms of use",
  block:
    "You cannot send the order because your membership has been banned by the administration !",
  receive_offers_status: "Waiting for your purchase offer",
  delivery_time_status: "Awaiting delivery date",
  on_way_status: "We are on our way to you",
  on_site_status: "We are on our site to you",
  ladder_status: "The deal is closed",
  changePassword: "Change Password",
  old_password: "Old Password",
  new_password: "New Password",
  confiem_password: "Confirm New Password",
  error_password: "كلمة المرور القديمة خاطئة !",
  error_password_title: "خطأ",
  success_password: "تم تغيير كلمة المرور بنجاح !",
  success_password_title: "تم التغيير",
  error_auth: "Please make sure that you have entered all fields !",
  account_type: "Type Account",
  account_type_des: "Choose the account you want to take advantage of",
  user: "User",
  provider: "Provider",
  Next: "Next",
  goLogin: "Sign in",
  information_account: "Account details",
  information_account_des:
    "Enter the account information to complete the registration process successfully",
  Photo: "Photo",
  error_phonee:
    "Error, please make sure that you have entered the correct phone field",
  service_type: "Service type",
  service_type_des: "Choose the type of service you want to provide",
  city: "City",
  governorate: "Governorate",
  select_city: "Select City",
  select_governorate: "Select Governorate",
  cover: "Identity",
  service_random: "Popular services",
  more: "Read More",
  services: "Services",
  services_des: "Choose the service you want",
  services_selected: "Required service",
  spicified_address: "Specific address",
  spicified_appoitment: "Specific time",
  complete_order: "Complete Order",
  add_service: "Add Service",
  add_address: "New addition",
  add_address_new: "Add a new address",
  cat_address: "Category address",
  home: "Home",
  office: "Office",
  other: "Other",
  des_address: "Address description",
  select_address_map: "Determine the address on the map",
  confirm_address: "Confirm Address",
  Select_location: "Select location",
  select_address_map_done: "Address was selected successfully",
  success: "done successfully ",
  success_des: "The data has been sent successfully !",
  day_selected: "When do you want the service to start",
  time_selected: "Choose the right time",
  description_service: "Description Service",
  image_service: "Attach photos for help",
  optinal: "optional",
  thanks: "Thank you",
  thanks_des: "Your request has been sent successfully",
  order_num: "Order number",
  details_order: "Follow the order details",
  back_home: "Back to home",
  my_orders: "My Orders",
  order_date: "Date Order",
  new: "New",
  in_progress: "Progress",
  completed: "Completed",
  canceled: "Canceled",
  offers_order: "Offers Order",
  watch: "Watch",
  order_details: "Order Details",
  order_canceled: "Cancelling order",
  View_status: "View by status",
  chat: "Chat",
  appoitment: "Appoitment",
  day: "Day",
  date: "Date",
  time: "Time",
  images: "Images",
  all: "All",
  offer_waiting: "Waiting to choose one of the offers made",
  riyal: "Rial",
  accept_offers: "Accept Offre",
  View_status_price: "Display by price",
  write_msg: "Write Msg",
  complete_order: "Complete Order",
  chating: "Chating",
  Complete_order: "The chat is closed due to the completion of the project ",
  canceled_order: "Chat is closed due to cancellation of the project",
  my_wallet: "My Wallet",
  log_wallet: "Wallet Log",
  account_setting: "Account Setting",
  user_policy: "Usage policy , terms and conditions",
  ads: "Ads",
  about: "About App",
  share_app: "Share App ",
  sign_out: "Sign Out ",
  more_page: "More",
  change_lang: "Change Language",
  change_password: "Change Password",
  apply: "Apply",
  cancel: "Cancel",
  conditions: "Terms and Conditions",
  user_policyy: "Usage Policy",
  error_pass: "The entered passwords do not match",
  old_password_incorrect: "The old password is incorrect !",
  order_in_progress: "Orders in progress",
  money: "Payments",
  last_orders: "Last Orders",
  add_offers: "Add Offer",
  Average_offers: "Average offers",
  my_offers: "My offers",
  offers_price: "Your offer value",
  new_offer: "Waiting to accept your offer from the beneficiary",
  inprogress_offer:
    "Waiting for the application to be finalized and the service evaluation from the beneficiary",
  my_profile: "My Profile",
  public_info: "Public information",
  select_payment: "Choose a payment method",
  name_cart: "Name of the cardholder",
  name_number: "Card number",
  expire: "Expiry date",
  cvc: "CVC",
  msg: "Messages",
  show_location: "Show location",
  request_Cancelling_order: "Cancellation order",
  request_Cancelling_order_des:
    "You have a cancellation request for this project",
  edit_cat: "Edit Services",
  close_rating: "Close and Rating",
  close_rating_des:
    "When the request is completed, the chat is closed and the service providers dues are transferred",
  price_less: "Less than 100",
  price_more: "More than 100",
  enter_code: "Enter the code",
  endet_code_des: "Enter the code sent to your phone number",
  enter_pass: "Enter password",
  enter_pass_des: "Enter the new password",
  check_user: "Wait for the activation of your account from the administration",
  pending_wallet: "Pending Wallet",
  avilable_wallet: "Avilable Wallet",
  withdraw: "Withdraw",
  login_visitor: "Browse without register",
  login_s: "Please login to be able to view all data",
  pending: "Activation",
  pending_des: "Waiting for the account to be activated by the administration",
  notification_disable: "Turn off notifications",
  request_finished_orders: "Request to complete the project",
  request_finished_orders_des:
    "The service provider requested termination and evaluation of the project",
  edit_offer: "Edit offer",
  des_edit:
    "Note: A notification will be sent if the beneficiary approves the price amendment",
  edit_msg: "Modification sent",
  edit_msg_des: "Send a request for modification has been successfully !",
  edit_msg_des_pages: "A request to amend the bid price has been sent",
  approved: "approved",
  disapproved: "disapproved",
  edit_s: "The offer has been successfully modified !",
  edit_false: "Amendment rejected",
  edit_s_false: "The amendment rejected the offer price successfully !",
};

const ar = {
  username: "اسم المستخدم",
  phone: "الهاتف",
  gold: "ذهب",
  Ingots: "سبائك",
  no_cat: "لا يوجد تصنيفات",
  no_image: "لا يوجد صور",
  search: "بحث في الخريطة",
  order: "الطلبات",
  new: "جديد",
  approved: "تمت الموافقة",
  disapproved: "مرفوضة",
  check_field: "يرجى التأكد من ادخال كافة الحقول",
  login: "تسجيل دخول",
  fail_login: "فشل تسجيل الدخول",
  go_to_home: "سيتم تحويلك الى الصفحة الرئيسية",
  error_login: "البريد الالكتروني او كلمة المرور خاطئة !",
  email: "البريد الالكتروني",
  password: "كلمة المرور",
  forget_password: "نسيت كلمة المرور ؟",
  no_account: "ليس لديك حساب ؟",
  create_account: "قم بانشاء حساب الان",
  forget_password_title: "نسيت كلمة المرور ",
  forget_password_des: "ستصلك رسالة على البريد الالكتروني الذي قمت بادخاله",
  forget_password_dess: "ستصلك رسالة على رقم الهاتف الذي قمت بادخاله",
  send: "ارسال",
  resend: "اعادة ارسال",
  signUp: "انشاء حساب جديد",
  signUp_des: "ادخل بياناتك",
  agree: "اوافق على",
  Privacypolicy: "سياسة الخصوصية",
  signAlreadyAccount: "هل تمتلك حساب ؟",
  signAlreadyAccountNo: "لا تمتلك حساب ؟",
  signlogin: "أدخل رقم هاتفك لتسجيل الدخول",
  sign_done_des: "بالضغط على زر المتابعة سوف تتلقى رسالة للتحقق من الهاتف",
  sign_done: "تم التسجيل",
  check_username: "الرجاء التأكد من حقل اسم المستخدم",
  check_phone: "الرجاء التأكد من حقل الهاتف",
  check_email: "الرجاء التأكد من حقل البريد الالكتروني ",
  check_password: "يجب ان تحتوي كلمة المرور على 7 خانات على الاقل",
  user_policy_check: "لا يمكن التسجيل الا بالموافقة على شروط استخدم التطبيق",
  error_auth: "الرجاء التأكد من ادخالك كافة الحقول !",
  no_order: "لا يوجد عناصر",
  number_order: "رقم الطلب",
  date_order: "تاريخ الطلب",
  name_order: "اسم الطلبية",
  total: "المجموع",
  no_item: "لا يوجد عناصر",
  show_item: "تصفح المنتجات",
  cart: "السلة",
  confirm: "تم التأكيد",
  reject: "تم الرفض",
  reject_des:
    "لديك طلبية سابقة لم يتم تأكيدها , يرجى الانتظار الى ان يتم تأكيدها",
  confirm_des: "تم ارسال طلبيتك الى الادارة , سيتم مراجعتها والرد عليك",
  product: "منتج",
  all_product: "كافة المنتجات",
  stores: "المتاجر",
  cat_stores: "تصنيفات المتجر",
  all_cat_stores: "كافة التصنيفات",
  alloy_product: "منتجات السبائك",
  gold_product: "منتجات الذهب",
  other_product: "منتجات اخرى",
  add_to_cart: "اضافة الى السلة",
  product_same: "منتجات مشابهه",
  alloy: "سبائك",
  add_done: "تم الاضافة بنجاح",
  add_done_des:
    "تم اضافة المنتج الى السلة , بامكانك الاطلاع على كافة المنتجات في السلة",
  profile: "الملف الشخصي",
  favorite: "المفضلة",
  gold_price: "أسعار الذهب",
  offers: "العروض",
  logout: "تسجيل خروج",
  suggision: "شكوى او اقتراح",
  help: "مساعدة",
  contact: "تواصل معنا",
  About_Us: "عن التطبيق",
  share: "مشاركة التطبيق",
  language: "اللغة",
  advertisment: "الاعلانات",
  orders: "طلباتي",
  special_request: "اضافة طلب خاص",
  send_done: "تم الارسال بنجاح",
  send_done_des: "تم ارسال البيانات الى الادارة بنجاح",
  address: "العنوان",
  my_address: "عناويني",
  description: "الوصف",
  title: "عنوان الموضوع",
  title_pro: "عنوان المقترح",
  title_com: "عنوان الشكوى",
  des_pro: "وصف المقترح",
  des_com: "وصف الشكوى",
  Complaint: "شكوى",
  Suggestion: "مقترح",
  Skip: "تخطى",
  edit_profile: "تعديل الملف الشخصي",
  last_updated: "اخر تحديث",
  caliber: "العيار",
  price: "السعر",
  sum: "المجموع",
  confirmCart: "تأكيد",
  login_order: "قم بتسجيل الدخول لعرض طلباتك",
  notification: "الاشعارات",
  SettingApp: "انتظر قليلا ، جاري اعداد التطبيق",
  change_photo: "تغيير الصورة",
  save: "حفظ",
  save_done: "تم الحفظ",
  save_done_des: "تم حفظ البيانات بنجاح",
  no_id_save_cart: "لا يمكنك الاضافة بالسلة , قم بتسجيل الدخول اولاً",
  gold_text:
    "تصفح كافة تصنيفات الذهب ومنتجات المجوهرات والذهب وقم باضافته الى السلة وتقديم طلب شراء للمنتج  ",
  Categories: "تصنيفات",
  alloy_text:
    "تصفح كافة تصنيفات السبائك ومنتجات السبائك بانواعها المختلفة وقم باضافة المنتجات الى السلة وتقديم طلب شراء",
  zinah: "متجر زينة للمجوهرات",
  submit_follow_up_request: "تقديم طلب بيع",
  quantity: "الكمية",
  Tons: "طن",
  your_map: "موقعك",
  payment_type: "الطريقة التي تفضل استلام المبلغ",
  cash: "نقداً",
  change: "تغيير",
  contact_customer_service: "اتصل بخدمة العملاء",
  send_email: "ارسال ايميل",
  hide: "اخفاء",
  select_payment_method: "حدد طريقة الدفع",
  cash_method: "الدفع عند الاستلام",
  add_bank: "اضافة حساب بنكي",
  add_bank_new: "اضافة حساب بنكي",
  done: "تم",
  edit: "تعديل",
  delete: "حذف",
  Account_management: "ادارة الحسابات",
  account_owner: "اسم مالك الحساب",
  number_account: "رقم الحساب",
  bank_name: "اسم البنك",
  add_done: "تمت الاضافة",
  add_done_des: "تمت الاضافة بنجاح !",
  history: "السجل",
  receive_offers: "مرحلة تلقي العروض",
  on_way: "في الطريق",
  on_site: "في الموقع",
  ladder: "تم تسليمها",
  canceled: "تم الغائها",
  rejected_user: "مرفوضة",
  deliverd_on: "تم تسليمها في",
  order_id: "رقم الطلب",
  price_order: "سعر الصفقة",
  details_order: "عرض تفاصيل الطلب",
  order_details: "تفاصيل الطلب",
  order_status: "حالة الطلب",
  order_date: "تاريخ الطلب",
  date_deliverid: "موعد الاستلام",
  location_in_map: "الموقع على الخريطة",
  follow_order: "متابعة طلبك",
  no_price: "",
  purchase_offer: "عرض الشراء المقدم",
  Cancelling_order: "الغاء الطلب",
  show: "عرض",
  approv: "قبول",
  rejec: "رفض",
  Communication_service: "التواصل مع خدمة العملاء",
  done_order: "تم ارسال طلبك بنجاح",
  done_order_des:
    "قد يستغرق حصولك على عرض شراء من 1 - 24 ساعة عمل . للاستفسارات يمكنك التواصل مع",
  customers_service: "خدمة العملاء",
  name: "الاسم",
  address: "عنوانك بالتفصيل",
  select_map: "تحديد موقعك",
  select_map_done: "تم تحديد موقعك بنجاح",
  hello_coi: "مرحباً بك في COI",
  sign: "تسجيل جديد",
  check: "تحقق",
  check_phone: "التحقق من رقم الهاتف",
  check_phone_des: "أدخل رقم التحقق المرسل الى هاتفك",
  add_code: "ادخل الكود",
  add_code_des: "ادخل الكود لتتمكن من تغيير الرقم الخاص بك",
  success: "تم التغيير بنجاح",
  success_des: "تم التغيير بنجاح",
  errorr: "خطأ",
  errorr_des: "الكود الذي ادخلته خاطئ !",
  rating_success: "مبروك",
  rating_success_des: "تم انهاء الصفقة بنجاح",
  your_opinion: "رأيك يهمنا",
  rating_text_success: "تم التقييم",
  rating_text_success_des: "تم اضافة تقييمك للطلب بنجاح !",
  Home: "ارسال طلب",
  ChangeNumber: "تغيير الرقم",
  AddBank: "ادارة الحسابات",
  ChangeLanguage: "تبديل اللغة",
  UserPolicy: "سياسة الخصوصية وشروط الاستخدام",
  block: "لا يمكنك ارسال الطلبية بسبب حظر عضويتك من قبل الادارة !",
  receive_offers_status: "في انتظار عرض الشراء",
  delivery_time_status: "في انتظار موعد التسليم",
  on_way_status: "نحن في طريقنا اليك",
  on_site_status: "متواجدون في الموقع",
  ladder_status: "تم انهاء الصفقة",
  changePassword: "تغيير كلمة المرور",
  old_password: "كلمة المرور القديمة",
  new_password: "كلمة المرور الجديدة",
  confiem_password: "تأكيد كلمة المرور الجديدة",
  error_password: "كلمة المرور القديمة خاطئة !",
  error_password_title: "خطأ",
  success_password: "تم تغيير كلمة المرور بنجاح !",
  success_password_title: "تم التغيير",
  account_type: "نوع الحساب",
  account_type_des: "اختر الحساب الذي تريد الاستفاده منه",
  user: "مستفيد",
  provider: "مقدم خدمة",
  Next: "التالي",
  goLogin: "قم بتسجيل الدخول",
  information_account: "بيانات الحساب",
  information_account_des: "أدخل بيانات الحساب لتتم عملية التسجيل بنجاح",
  Photo: "الصورة الشخصية",
  error_phonee: "خطأ , الرجاء التأكد من ادخالك حقل الهاتف بالشكل الصحيح",
  service_type: "نوع الخدمة",
  service_type_des: "اختر نوع الخدمة التي تريد تقديمها",
  city: "المدينة",
  governorate: "المحافظة",
  select_city: "اختر المدينة",
  select_governorate: "اختر المحافظة",
  cover: "الهوية",
  service_random: "الخدمات الشائعة",
  more: "عرض المزيد",
  services: "الخدمات",
  services_des: "اختر الخدمة التي تريدها",
  services_selected: "الخدمة المطلوبة",
  spicified_address: "تحديد العنوان",
  spicified_appoitment: "تحديد الموعد",
  complete_order: "اكتمال الطلب",
  add_service: "اضافة طلب جديد",
  add_address: "اضافة جديد",
  add_address_new: "اضافة عنوان جديد",
  cat_address: "تصنيف العنوان",
  home: "المنزل",
  office: "المكتب",
  other: "عنوان اخر",
  des_address: "وصف العنوان",
  select_address_map: "تحديد العنوان على الخريطة",
  confirm_address: "تأكيد الموقع",
  Select_location: "اختر الموقع",
  select_address_map_done: "تم تحديد العنوان بنجاح",
  success: "تم بنجاح ",
  success_des: "تم ارسال البيانات بنجاح !",
  day_selected: "متى تريد أن تبدأ الخدمة",
  time_selected: "اختر الوقت المناسب",
  description_service: "َأضف تفاصيل للمساعدة",
  image_service: "ارفاق صور للمساعدة",
  optinal: "اختياري",
  thanks: "شكرا لك",
  thanks_des: "تم ارسال طلبك بنجاح !",
  order_num: "رقم الطلب",
  details_order: "تابع تفاصيل الطلب",
  back_home: "العودة الى الرئيسية",
  my_orders: "طلباتي",
  order_date: "تاريخ الطلب",
  new: "جديد",
  in_progress: "قيد التنفيذ",
  completed: "مكتمل",
  canceled: "ملغي",
  offers_order: "العروض المقدمة",
  watch: "مشاهدة",
  order_details: "تفاصيل الطلب",
  order_canceled: "الغاء الطلب",
  View_status: "عرض حسب الحالة",
  chat: "الدردشة",
  appoitment: "الموعد",
  day: "اليوم",
  date: "التاريخ",
  time: "الوقت",
  images: "الصور",
  all: "الكل",
  offer_waiting: "في انتظار اختيار أحد العروض المقدمة",
  riyal: "ريال",
  accept_offers: "قبول العرض",
  View_status_price: "عرض حسب السعر",
  write_msg: "أكتب رسالة",
  complete_order: "انهاء الطلب",
  chating: "مراسلة",
  Complete_order: "الدردشة مغلقة بسبب اكتمال المشروع ",
  canceled_order: "الدردشة مغلقة بسبب الغاء المشروع ",
  my_wallet: "محفظتي",
  log_wallet: "السجل المالي",
  account_setting: "اعدادات الحساب",
  user_policy: "سياسة الاستخدام والشروط والاحكام",
  ads: "الاعلانات",
  about: "عن التطبيق",
  share_app: "مشاركة التطبيق ",
  sign_out: "تسجيل خروج ",
  more_page: "المزيد",
  change_lang: "تغيير اللغة",
  change_password: "تغيير كلمة المرور",
  apply: "تطبيق",
  cancel: "الغاء",
  conditions: "الشروط والاحكام",
  user_policyy: "سياسة الاستخدام",
  error_pass: "كلمات المرور المدخلة غير متطابقة",
  old_password_incorrect: "كلمة المرور القديمة غير صحيحة !",
  order_in_progress: "طلبات قيد التنفيذ",
  money: "دفعات مالية",
  last_orders: "اخر الطلبات",
  add_offers: "تقديم عرض",
  Average_offers: "متوسط العروض",
  my_offers: "عروضي",
  offers_price: "قيمة عرضك",
  new_offer: "في انتظار قبول عرضك من المستفيد",
  inprogress_offer: "في انتظار انهاء الطلب وتقييم الخدمة من المستفيد",
  my_profile: "حسابي",
  public_info: "معلومات عامة",
  select_payment: "اختر طريقة الدفع",
  name_cart: "اسم حامل البطاقة",
  name_number: "رقم البطاقة",
  expire: "تاريخ الانتهاء",
  cvc: "CVC",
  msg: "الرسائل",
  show_location: "عرض الموقع",
  request_Cancelling_order: "طلب الغاء",
  request_Cancelling_order_des: "لديك طلب الغاء لهذا المشروع",
  edit_cat: "تعديل الخدمات",
  close_rating: "انهاء وتقييم",
  close_rating_des:
    "عند انهاء الطلب يتم اغلاق الدردشة وتحويل مستحقات مزود الخدمة",
  price_less: "اقل من 100",
  price_more: "اكثر من 100",
  enter_code: "أدخل الكود",
  endet_code_des: "أدخل الكود المرسل الى رقم هاتفك",
  enter_pass: "أدخل كلمة المرور",
  enter_pass_des: "أدخل كلمة المرور الجديدة",
  check_user: "انتظر تفعيل حسابك من الادارة",
  pending_wallet: "الرصيد المعلق",
  avilable_wallet: "الرصيد المتاح",
  withdraw: "السحب",
  login_visitor: "تصفح بدون تسجيل",
  login_s: "يرجى تسجيل الدخول لتتمكن من عرض كافة البيانات",
  pending: "تفعيل",
  pending_des: "في انتظار تفعيل الحساب من قبل الادارة",
  notification_disable: "ايقاف الاشعارات",
  request_finished_orders: "طلب انهاء المشروع",
  request_finished_orders_des: "طلب مزود الخدمة انهاء المشروع وتقييمه",
  edit_offer: "تعديل العرض",
  des_edit:
    "ملاحظة : سيتم ارسال اشعار في حال الموافقة على تعديل السعر من قبل المستفيد",
  edit_msg: "تم ارسال التعديل",
  edit_msg_des: "تم ارسال طلب التعديل بنجاح !",
  edit_msg_des_pages: "تم ارسال طلب تعديل سعر العرض الى",
  approved: "موافق",
  disapproved: "غير موافق",
  edit_s: "تم الموافقة على تعديل العرض بنجاح !",
  edit_false: "رفض التعديل",
  edit_s_false: "تم رفض تعديل سعر العرض بنجاح !",
};

i18n.fallbacks = true;
i18n.translations = { ar, en };

// AsyncStorage.clear().then((token) => {
//
//});

export default i18n;
